name: movie_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scroll_snap_list: ^0.9.1
  rubber: ^1.1.0
  pod_player: ^0.2.1
  http: ^1.1.0
  provider: ^6.0.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.14.0
  lottie: any
  country_picker: ^2.0.15
  cloud_firestore: ^4.9.1
  flutter_otp_text_field: ^1.1.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/loties/
  fonts:
    - family: Open-Sans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 300
        - asset: assets/font/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/font/OpenSans-ExtraBold.ttf
          weight: 800
